#!/bin/bash

# Programs
PYTHON="python3"                        # Python version installed (3 or above)

# Directories
SCRIPTS_DIR="./"                        # The directory for scripts
EXPORT_DATA="../jobs"                   # Location to export run data

# Files
INPUT="visc.in"                         # The LAMMPS input file
THERMO="system_nvt.txt"                 # File containing thermodynamic data
VISC="visc_nvt.txt"                     # The viscosity of the run
TEMP="temperature.txt"                  # The temperature of the run

# Parameters
VISC_CUT="1e-1"

# Extract data
${PYTHON} ${SCRIPTS_DIR}fragility.py\
	"-d${EXPORT_DATA}"\
	"-v${VISC}"\
	"-n${THERMO}"\
	"-t${TEMP}"\
	"-c${VISC_CUT}"\
