#!/bin/bash

# Programs
PYTHON="python3"                        # Python version installed (3 or above)

# Directories
SCRIPTS_DIR="./"                        # The directory for scripts
DATA="../viscosity_runs"                # Directory were data is stored
EXPORT_DATA="../viscosity_runs_data"    # Location to export run data
EXPORT_PLOTS="../viscosity_runs_plots"  # Location to export run plots


# Files
INPUT="visc.in"                         # The LAMMPS input file
TRAJ="traj_nvt.lammpstrj"               # File containing trajectories
THERMO="system_nvt.txt"                 # File containing thermodynamic data
VISC="visc_nvt.txt"                     # Viscosity data
TEMP="temperature.txt"                  # The temperature of the run

# Extract data
${PYTHON} ${SCRIPTS_DIR}gather_data.py\
	"-p${DATA}"\
	"-d${EXPORT_DATA}"\
	"-w${EXPORT_PLOTS}"\
	"-i${INPUT}"\
	"-s${THERMO}"\
	"-t${TRAJ}"\
	"-l${TEMP}"\
	"-v${VISC}"\
